---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: kpm-registry
  name: kpm-registry
spec:
  type: {{svc_type}}
  ports:
    - port: 80
      targetPort: 5000
      name: kpm-registry
  selector:
    k8s-app: kpm-registry
